### ISSUE TITLE
Update-v0.3.x-alpha Master Bug

### ISSUE THREAD

**Issue by m-nt** [atlasgames-repo/fortress-defense#123]
### Tasks
* [space]  - `<Title>` | `<Link to the comment>` | `<Link to the PR>`
* [x] Font Bug | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1964683217 | https://github.com/atlasgames-repo/fortress-defense/pull/125
* [x] Next Button For World Changes | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1964690080 | https://github.com/atlasgames-repo/fortress-defense/pull/126
* [x] Running Game in the Background | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1964700074 | https://github.com/atlasgames-repo/fortress-defense/pull/124
* [x] Archer upgrade problem | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1964702095 | https://github.com/atlasgames-repo/fortress-defense/pull/126
* [x] Health Bar Transform | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1964704264 | https://github.com/atlasgames-repo/fortress-defense/pull/128
* [x] Low Res Target UI | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1966388188 | https://github.com/atlasgames-repo/fortress-defense/pull/124/commits/6c72d84bdb4197bfb4ed2156c8971baf1321a43d
* [x] Menus Title logo and text | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1966384026 | https://github.com/atlasgames-repo/fortress-defense/pull/126
* [x] Magics Playing and Damaging in the background | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1967492740 | #Low_Priority_For_Later
* [x] Mobile Build Bug 1 (Slider) | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1968776684 | https://github.com/atlasgames-repo/fortress-defense/pull/124/commits/cfaa76990c67c4b48c135901f0026b72a95c4d91
* [x] Mobile Build Bug 2 (Event menu) | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1968781128 | https://github.com/atlasgames-repo/fortress-defense/pull/124/commits/1f4a02db736df7494c32052fc2f306525aedc3b4
* [x] Mobile Build Bug 3 (Guide Book) | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1968783618 | https://github.com/atlasgames-repo/fortress-defense/pull/124/commits/90e0474fe5d31c15308df85acbf6f5ccab143dc6
* [x] Mobile Build Bug 4 (Victory Menu) | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1968786587 | https://github.com/atlasgames-repo/fortress-defense/pull/124/commits/8ef845b34cc4835ec6ba5c24259f0021ad6a27cb
* [x] Guide Book open and close problem | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1968809302 | #Low_Priority_For_Later
* [x] Mobile Build Problem For icons | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1968818125 | #Low_Priority_For_Later
* [x] Archers miss a lot | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1969286396 | https://github.com/atlasgames-repo/fortress-defense/pull/124/commits/49d55e6e7b0b5c69a10a8f6b34ca13e228b38aba
* [x] Win and lose at the same time | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1970550631 | #Low_Priority_For_Later
* [x] Thunder Magic Boundary | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1970820219 | #Low_Priority_For_Later
* [x] Background of the World 5-6 | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1973944003 | https://github.com/atlasgames-repo/fortress-defense/pull/124/commits/1f4a02db736df7494c32052fc2f306525aedc3b4
* [x] Magics Background Bug | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1973956246 | #Low_Priority_For_Later
* [x] Archers Place In Pause Mode | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1974877355 | https://github.com/atlasgames-repo/fortress-defense/pull/128
* [x] Start And Pause At The Same Time | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1979483729 | #Low_Priority_For_Later
* [x] Boss / Miniboss Walk Line | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1979485600 | https://github.com/atlasgames-repo/fortress-defense/pull/124/commits/9153b8e5fc1030110609232e6c74e2aac6321cfc
* [x] The Bug of using multiple magic | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1986333513 | #Low_Priority_For_Later
* [x] Affect Zone Color | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1986338863 | #Low_Priority_For_Later
* [x] Level Bug From Login Menu | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-1986379481 | https://github.com/atlasgames-repo/fortress-defense/pull/137
* [x] Mobile Login Menu Font Bug | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-2040600173 | https://github.com/atlasgames-repo/fortress-defense/pull/137
* [x] Mobile Tutorial And Load Levels Scene Bug | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-2040603808 | https://github.com/atlasgames-repo/fortress-defense/pull/137
* [x] Mobile Damage Text Recommendation | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-2040605890 | https://github.com/atlasgames-repo/fortress-defense/pull/137
* [ ] Mobile Loading Scene Problem | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-2046574942
* [x] Enemy with no attack damage | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-2117825337
* [ ] Range enemy with no attack damage | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-2125098362
* [ ] Thunder magic with no damage | https://github.com/atlasgames-repo/fortress-defense/issues/123#issuecomment-2143860346

**Comment by m-nt** [comment]
Font Bug
I think the font used in the game doesn't have (( / )) (Slash), that's why it won't be rendered the slash(/) in the place of showing the world you are in from the remaining worlds.

Nooo, I check the font in the google and it has the slash.

**Comment by m-nt** [comment]
### Next Button For World Changes
The levels go back and forth very quickly and this makes the fade animation ugly and square like. I think it takes 1 second for each click to move forward.
In the MapControllerUI you need to add the time to IEnumerator.

**Comment by m-nt** [comment]
### Running Game in the Background
Even when you win or lose you can mark the archer!
if you want tell me in the telegram to send the video for you.

**Comment by m-nt** [comment]
### Archer upgrade problem
When you press upgrade so fast, archer will update a few further, for example, if you press 2 times quickly, it may update the archer 3 times, but if you press upgrade normally, it is ok.

**Comment by m-nt** [comment]
### Health Bar Transform
The Transform of the health bar is so above the enemy or even don't show!!

**Comment by NimaDevy** [comment]
The Atlas Game Logo in the Menu Atlas / Home Menu / Home has problem. The arrow is behind the Text.

**Comment by NimaDevy** [comment]
The Target Sprite in AtlasGames/Sprites/UI's has low resolution, especially when the screen is maximize.

**Comment by NimaDevy** [comment]
World 8 : Has two boss icon over the level 75 and 80.
World 3 : Has 3 mini boss.

**Comment by NimaDevy** [comment]
When you use magic in the last moments of winning or losing, the magic still damages the enemy even when you win or lose. 
For example: I use the magic of thunder, and even when I lose, it still activates and damages the player.

**Comment by NimaDevy** [comment]
### Mobile Build Bug 2 (Event menu)
1- In the event menu the events are too far from the left side.
![2](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/50706551-6c87-4ec9-b137-53ccf0e4555c)

**Comment by NimaDevy** [comment]
### Mobile Build Bug 3 (Guid Book)
1-  When you open the guide book the pause menu set active goes to true.
![3](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/ab350e7c-0caf-47af-88de-43906c0e9251)

**Comment by NimaDevy** [comment]
Mobile Build Bug 4 (Victory Menu)
1- In the victory menu the placement of stars or chests is very bad.
![4](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/cd16978b-1078-4d9c-a2a6-1e98b7abaf16)

**Comment by NimaDevy** [comment]
### Guide Book
When you open and close the manual, the icon in the lower right corner will open and close.

**Comment by NimaDevy** [comment]
### Guide Book
When you open and close the manual, the icon in the lower right corner will open and close.

Uploading Bug.mp4…

**Comment by NimaDevy** [comment]
### Guide Book
When you open and close the manual, the icon in the lower right corner will open and close.

https://github.com/atlasgames-repo/fortress-defense/assets/98099665/a23e2015-7d25-4995-9457-60f2b5496d14

**Comment by NimaDevy** [comment]
### Mobile Buid Problem For icons
The icons in the game is very small and har to click in mobile.

**Comment by NimaDevy** [comment]
### Archers miss a lot
When the enemy is very close to the castle, the archers miss a lot of shots every time!
![Uploading image_2024_02_28T13_38_19_436Z.png…]()

**Comment by NimaDevy** [comment]
### Archers miss a lot
When the enemy is very close to the castle, the archers miss a lot of shots every time!
![Bug](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/1bca9e6a-20ee-4e52-9b39-7e1eb7115ec6)

**Comment by m-nt** [comment]
> ### Mobile Buid Problem For icons
> The icons in the game is very small and har to click in mobile.
@NimaDevy 
Can you specify the type of phone and its details like aspect ratio etc...

**Comment by NimaDevy** [comment]
### Archers miss a lot
When the enemy is very close to the castle, the archers miss a lot of shots every time! especially when the enemy is in the one line.
![Uploading Bug.png…]()

**Comment by NimaDevy** [comment]
###Win and lose at the same time
I was testing the game, the health of the castle was 3 and in the last moment I killed the enemy and he attack to the castle(at the same time).
UI crashed and show the win pannel and the lose pannel at the same time.

**Comment by NimaDevy** [comment]
### Background Music
If you win or lose or pause and wait for a few minutes the background music don't play.
I think it's in the audio soure component for music, check for the loop section to be active.

**Comment by NimaDevy** [comment]
Magics boundary is very open. It damages the enemy that is close to it too.
![Capture](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/9ecdc161-3d8a-4d08-b555-37defdc4606e)

**Comment by NimaDevy** [comment]
### Boss/MiniBoss Health Bar
In the levels 10, 15, 20 and etc, there is a health bar on the head of the enemy but there is a big health bar also. you need to disable the first one and the enemy is boss or miniboss.
![bug](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/a7213035-347d-44dd-9c53-dff05a648c3d)

**Comment by NimaDevy** [comment]
### Background of the levels
Levels 40 - 60 (World5 and World6) has very low quality background and also this cause to enemys seem that are ouside the map.
![bug4](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/e446dcb4-725e-4fee-9ad8-36ace3dc1d53)

**Comment by NimaDevy** [comment]
### Magics
When you select the magic but not selecting the slot it needs to damage, and then you win or lose, the select sprite remains in the background.
![Capture](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/7603639d-c42b-4747-928d-4ed86e30b254)

**Comment by NimaDevy** [comment]
### Loading Scene Sprite
In this photo, pay attention to the middle photo, it is not attached to the top
It means that the scale is not correct.
![photo_5978630090357064291_y](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/73501069-6570-404e-b0ab-d3630e5829b8)

**Comment by NimaDevy** [comment]
### Archer Place In Pause Mode
When you are in pause screen you can place the archers.

https://github.com/atlasgames-repo/fortress-defense/assets/98099665/6c25679f-1e74-4642-89ed-4476455a44ae

**Comment by m-nt** [comment]
> ### Mobile Build Problem For icons
> The icons in the game is very small and har to click in mobile.

@NimaDevy 
Need more details...

**Comment by m-nt** [comment]
> ### Win and lose at the same time
> I was testing the game, the health of the castle was 3 and in the last moment I killed the enemy and he attack to the castle(at the same time). UI crashed and show the win panel and the lose panel at the same time.

@NimaDevy 
Good job, but these type of error is very rare, and doesn't have that much priority.
I'll tag this for future plans.

**Comment by NimaDevy** [comment]
### Start The Game And Pause
When the game starts and I stop quickly, both panel images appear.
![photo_5996764747950835122_y](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/31917668-becc-45cc-9841-70a79e652704)

**Comment by NimaDevy** [comment]
### Boss / Miniboss Walk Line
It is much better if the boss or mini-boss comes only in the middle row(line).

**Comment by NimaDevy** [comment]
### Poison And Blizzard Bug
When you use blizzard magic and after that the poison, the enemies start moving
 instead of staying in place and taking damage. This is also true when you use blizzard and magent.
Also if you hear the last moment of the video the background sound connects and disconects when you use poison.
https://github.com/atlasgames-repo/fortress-defense/assets/98099665/5becfe0a-a6a9-40fb-9b6c-892c31545c22

**Comment by NimaDevy** [comment]
### Affect Zone Color Bug
I dont know why but sometimes the color of affect zone is this:
![photo_6006005395857981311_w](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/7735960b-3e6a-4867-a5cc-f303934b268d)

**Comment by NimaDevy** [comment]
### Mobile Build Bug (Loading in home menu scene)
After downloading the necessary assets, when the menu page comes up, no button works and the animations do not play and...
My suggestion is like the call of duty mobile, after downloading data, a new panel should appear as Loading Data, then this panel should come to load the game, for example, the simple text Loading can appear on the panel.
But when it's over, the player can play from the beginning and doesn't have to wait two minutes for the game to load.

**Comment by NimaDevy** [comment]
### Level Bug From Login Menu
I have a problem. I checked all levels up to level 100, but when I went to atlasgames/scene/login from the main game login page, only one level didn't work properly. level 15.

**Comment by m-nt** [comment]
> ### Poison And Blizzard Bug
> When you use blizzard magic and after that the poison, the enemies start moving instead of staying in place and taking damage. This is also true when you use blizzard and magnet. Also if you hear the last moment of the video the background sound connects and disconnects when you use poison. https://github.com/atlasgames-repo/fortress-defense/assets/98099665/5becfe0a-a6a9-40fb-9b6c-892c31545c22

Yes this is not a bug, its a feature 😁.
About the audio I didn't anything bad, the problem is the poison audio itself. its very bad.

**Comment by m-nt** [comment]
> ### Level Bug From Login Menu
> I have a problem. I checked all levels up to level 100, but when I went to atlasgames/scene/login from the main game login page, only one level didn't work properly. level 15.

How the level didn't work properly, please specify more details.

**Comment by Russell2023** [comment]
There is a problem with the gameplay. From levels 60 and so on, player might be able to use archer level 4th and 5th. These arches can slow down the enemies. For now we have no issue with normal enemies, however there is a problem with bosses/mini-bosses. I have to speed up the bosses so that the effect of archers won't make boss fights so easy. The problem is that the player might not reach archers level 4th and 5th which will make the boss fight too hard. Guess I explained it a bit complicated :)

As a solution, we might delete the slow down effect for bosses/mini-bosses.

**Comment by NimaDevy** [comment]
> There is a problem with the gameplay. From levels 60 and so on, player might be able to use archer level 4th and 5th. These arches can slow down the enemies. For now we have no issue with normal enemies, however there is a problem with bosses/mini-bosses. I have to speed up the bosses so that the effect of archers won't make boss fights so easy. The problem is that the player might not reach archers level 4th and 5th which will make the boss fight too hard. Guess I explained it a bit complicated :)
> 
> As a solution, we might delete the slow down effect for bosses/mini-bosses.

Yes, the mini-bosses or the bosses are so fast. I think it is better to apply only the damage of the archers and not change their speed

**Comment by NimaDevy** [comment]
### Mobile Login Menu Font Bug
When you set the password to Hide mode, it doesn't show anything, whether it is written or not, it is better to put <<....>> (dot) instead of nothing, for example .... .
![1712348417050](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/4ff29e15-b5f7-4af6-8b52-f2af76f09b5b)

**Comment by NimaDevy** [comment]
### Mobile Tutorial And Load Levels Scene Bug
The last tutorial panel of the game cannot be closed in the Main Menu scene, and also when the first startup of the scene, the levels do not come up and turn black but when you go into the game for the second time, it cames up.
![1712348417043](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/7956c7c5-2094-4d84-a10b-01128f092b77)

**Comment by NimaDevy** [comment]
### Mobile Damage Text Recommendation
Damage text for the floating text when the castle itself is damaged, I think it should be larger and more visible (only for the castle)
![1712348417040](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/4c7fd704-cf0c-4d5b-83b5-aa9e248e62dc)

**Comment by NimaDevy** [comment]
### Mobile Loading Scene Problem
I dont know why but in the slider there is a image that is stretching (Only in mobile, in the pc it is not like that).
![photo_2024-04-10_09-04-54](https://github.com/atlasgames-repo/fortress-defense/assets/98099665/a2ba4059-b4ad-426a-86df-65fd7acdf3e2)

**Comment by Russell2023** [comment]
Right after loading level 36 using level generator, the bottom half disappears. There might be other levels that can cause this problem so I will update this comment.

![fortress-defense - Playing atlas Test - PC, Mac   Linux Standalone - Unity 2020 2 5f1 Personal _DX11_ 4_30_2024 7_01_26 PM](https://github.com/atlasgames-repo/fortress-defense/assets/103450629/1c34e23d-35f0-487a-836d-6019afe7419e)

**Comment by Russell2023** [comment]
The game shows no UI after losing a level. This is the error I got:

UnassignedReferenceException: The variable LeaderBoardUI of MenuManager has not been assigned.
You probably need to assign the LeaderBoardUI variable of the MenuManager script in the inspector.
MenuManager+<GameOverCo>d__32.MoveNext () (at Assets/_FD/Script/GUI/MenuManager.cs:137)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <31d5d65b32ec483292e13e8ae4100b93>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
MenuManager:IGameOver() (at Assets/_FD/Script/GUI/MenuManager.cs:130)
GameManager:GameOver() (at Assets/_FD/Script/GameManager.cs:262)
TheFortrest:TakeDamage(Single, Vector2, Vector2, GameObject, BODYPART, WeaponEffect, WEAPON_EFFECT) (at Assets/_FD/Script/TheFortrest.cs:95)
EnemyMeleeAttack:Check4Hit() (at Assets/_FD/Script/SmartEnemy/EnemyMeleeAttack.cs:84)
SmartEnemyGrounded:AnimMeleeAttackStart() (at Assets/_FD/Script/SmartEnemy/SmartEnemyGrounded.cs:298)

**Comment by m-nt** [comment]
> ### Mobile Loading Scene Problem
> I dont know why but in the slider there is a image that is stretching (Only in mobile, in the pc it is not like that). ![photo_2024-04-10_09-04-54](https://private-user-images.githubusercontent.com/98099665/321113099-a2ba4059-b4ad-426a-86df-65fd7acdf3e2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MjcyODIsIm5iZiI6MTcxNDkyNjk4MiwicGF0aCI6Ii85ODA5OTY2NS8zMjExMTMwOTktYTJiYTQwNTktYjRhZC00MjZhLTg2ZGYtNjVmZDdhY2RmM2UyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDE2MzYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ODg5OTIxY2MxODQ4NGIzMDBjMWY0MDQyZmM3MjJiNTM3NWU3ZTBiMmJjZGQ5YjE5ZDFiYzZiOWU1YjIzNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uPneDsgY3wzzs55sYf7HeSMeJJNdeywB4q1BWJwIVsg)

please add these to the codecks as well as here. thanks @NimaDevy

**Comment by Russell2023** [comment]
On of the enemies (CrystalLizard) has no attack damage. Do we consider as a bug or it is easily customizable? @m-nt 

![fortress-defense - Playing atlas Test - PC, Mac   Linux Standalone - Unity 2020 2 5f1 Personal _DX11_ 5_17_2024 6_45_55 PM](https://github.com/atlasgames-repo/fortress-defense/assets/103450629/6a382154-6170-4e73-95eb-0e5275123be3)

**Comment by Russell2023** [comment]
Sometime range enemies don't have any damage to the castle. I think whenever there is another enemy in front of range enemies, the attack damage disappears.

**Comment by Russell2023** [comment]
We have a little problem wit thunder magic. It does have damage for the start, but after the first hit. ii won't affect the enemy anymore.

**Comment by Russell2023** [comment]
Player is able to move the castle health bar.

![fortress-defense - Playing atlas Testing - PC, Mac   Linux Standalone - Unity 2020 2 5f1 Personal _DX11_ 6_10_2024 6_27_20 PM](https://github.com/atlasgames-repo/fortress-defense/assets/103450629/1aef55cd-f7c9-4424-9791-a22e69f42fbc)
